source 'https://rubygems.org'

gem 'rake'
gem 'chefspec'
gem 'berkshelf'
gem 'bundler', '>1.10'

group :release do
  gem 'github_changelog_generator'
end

# Install omnibus software
group :omnibus do
  gem 'omnibus', git: 'https://github.com/chef/omnibus'
  #  gem 'omnibus-software', git: 'https://github.com/chef/omnibus-software'
  gem 'omnibus-software', git: 'https://github.com/chef/omnibus-software', branch: 'ma/newer_nodejs'
  # gem 'omnibus-software', path: '/home/vagrant/omnibus-software'
end

group :test do
  gem 'rspec'
end
